---
# tasks file for roles/webserver
- name: Install NGINX
  apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Copy NGINX Config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart NGINX

- name: Deploy Custom HTML Page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

    