
- name: Deploy Custom Web Page
  hosts: web_servers
  become: true
  tasks:
    - name: Deploy the template
      template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html
        